### ISSUE TITLE
Ctrl key disabled in text area?

### ISSUE THREAD

**Issue by garyhodgson** [box/mojito#152]
Hi, [it appears](https://github.com/box/mojito/blob/master/webapp/src/main/resources/public/js/components/workbench/TextUnit.js#L192) that the Ctrl key is explicitly disabled in the translation textarea of the web app which has the negatove side effect that pasting with Ctrl-v doesn't work, nor attempting to tyle any of the symbols from the numer row, e.g. "{" which is quite handy for parameter placeholders etc.

Is this really by design, or is there a particular use-case being served by disabling it?

**Comment by aurambaj** [comment]
Looks like at big nasty bug we didn't get because we all have Macs and use Command+V for copy pasting :)

the idea behind this code that to prevent the enter key to save the translation and instead introduce a new line in the string. To save the translation you'd to type ctrl+enter. 

This actually annoyed me last time I used it. Not sure in the case of software string it is so often we have return lines.

So as it is buggy... maybe we should just remove that feature.

@jeeyi @hkanabiajeuskaja thoughts?
