### ISSUE TITLE
Generate Java properties files with ISO-8859-1 encoding

### ISSUE THREAD

**Issue by jeeyi** [box/mojito#157]
By default, Java loads the properties files in ISO-8859-1.  Didier Tallot has requested an option to pull localized files in ISO-8859-1.

**Comment by aurambaj** [comment]
we could have an option for JAVA escaped properties files, introducing a 3rd type (start to be too much though?) in the CLI.

It would map maps exactly to Java properties format. Because the locale format we use in the current properties is not as expected as JAVA either. 

Okapi supports generation of escaped properties (actually that's the default processing). We set it up to use use the unescaped because we use properties files for something else that Java.
