### ISSUE TITLE
Caching support for push/pull

### ISSUE THREAD

**Issue by dragosv** [box/mojito#284]
Need to be able to only send the files that have changed, as if someone pushes 1000+ files daily, but most have not changed the push takes too long. Also this need to be a parameter on the CLI (--use-cache or similar). Should also support retrieving only the files that have changed as well. 

Currently (0.83) the push will only import changed translations. Would like to extend this to the import process, as for proper Serge.io (https://serge.io) integrations the updated translations also need to be reimported every time.

For pull, would take a look into the approach Zanata took (storing a cache database).

**Comment by aurambaj** [comment]
For the push, it is easy to implement. The backend stores Md5 of the assets so we can retrieve that and just check if the asset has changed client side. We're using something similar to delete "removed" asset. Right now we just fetch asset ids (to remove) but we could fetch more asset data to implement what you're saying.

Can you clarify what you mean by: "only import changed translations"? If it hasn't changed there is nothing to import. Would you want to update timestamps or something?

Pull is way more complex since we don't cache localized asset on the server side. They are always computed on the fly. Can you elaborate in what case you'd need this actually? I've never had a use case that would require to push so many files. I really want a tangible use case to consider implementing that. I really want to keep the system as simple as possible.

**Comment by dragosv** [comment]
Let's say there are 100 files in 30 languages, that would result in 3000 files to push / pull.

**Comment by dragosv** [comment]
Re import only changed translations, I was meaning only upload the translation files that have changed instead of pushing everyone to the server.

**Comment by aurambaj** [comment]
Ok, I see. `import` is the same complexity as `pull`. Today there is not an easy way to know if changes made to a repository (from simple changes like adding/removing a translation to more complex change like changing locale inheritance) will impact the localized files. So caching the localized files is not simple since we don't know when to invalidate the cache precisely and that could lead to stale data which is not acceptable when generating files. I need to think more about it. 

How long does it take today to generate all the files?

**Comment by dragosv** [comment]
Can take more than one hour for an import even when there are only 100 files or less that changed.

**Comment by aurambaj** [comment]
@dragosv Would you mind sharing the size of the files and if you've done some sort of performance test/profiling, what part is slow? eg. webservice calls vs server side computation, etc

**Comment by aurambaj** [comment]
I doubt will work on that medium term. Closing for now.
