### ISSUE TITLE
Shared translations across repos

### ISSUE THREAD

**Issue by mnich0ls** [box/mojito#674]
Is there a way to share translations across repos? I definitely like the idea of separate repositories for separate projects (or platforms), but we have a lot of overlap between these projects and it would be great to leverage previously completed translations to fill-in translations in other repos. 

Maybe I'm missing something in the configuration of the project. Or maybe this just isn't a common convention as certain phrases can have different meaning depending on the context. 

Would love to learn how to manage this problem effectively or better understand what other organizations are doing.

**Comment by aurambaj** [comment]
Yes, there is a command to copy translations. You could run that on a regular basis. 

The part to do cross repository leveraging is not very developed at the moment because the way we've been using Mojito is with another TMS that is used for translation and the more general leveraging. 

You can copy translations based on the source with exact match (text unit with same name match first): `mojito leveraging-copy-tm -m EXACT -s repo1 -t repo2`. If you use the exact same keys and comments across repository you can use `-m MD5` for a more precise match.

If the match is by `name + source`, the string will be marked as accepted (unless there are still multiple matches due to unused/different comments but that would be a corner case). If the match is only on the `source`,  the translation will be flag as "need translation".

**Comment by mnich0ls** [comment]
Ok that's great. I'll give that a shot. Thank you!

**Comment by mnich0ls** [comment]
This worked exactly as I had hoped! Thanks again!
