### ISSUE TITLE
docker-compose not working..

### ISSUE THREAD

**Issue by martijnmichel** [box/mojito#686]
How can I use mojito on my vps ? (ubuntu 18.04)

root@h2932281:~/mojito/docker# DOCKER_BUILDKIT=1 docker-compose up -d
Building webapp
Step 1/14 : FROM maven:3.5.4-jdk-8 as build
 ---> 985f3637ded4
Step 2/14 : RUN apt-get update && apt-get install -y build-essential python nodejs-legacy libpng-dev pngquant
 ---> Using cache
 ---> dc06657b6b23
Step 3/14 : VOLUME ["/tmp"]
 ---> Using cache
 ---> 75e0ad1e4763
Step 4/14 : WORKDIR /mnt/mojito
 ---> Using cache
 ---> 0e9fff274fd3
Step 5/14 : COPY . /mnt/mojito
 ---> 39d1c8670830
Step 6/14 : ENV PATH="/mnt/mojito/webapp/node/:${PATH}"
 ---> Running in a0a36c42a803
Removing intermediate container a0a36c42a803
 ---> 35fb5dbe5446
Step 7/14 : RUN --mount=type=cache,target=/root/.m2 --mount=type=cache,target=/mnt/mojito/node --mount=type=cache,target=/mnt/mojito/node_module mvn clean install -DskipTests
ERROR: Service 'webapp' failed to build: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

**Comment by martijnmichel** [comment]
after changing the RUN function to include buildkit env var I get another error:
/bin/sh: 1: --mount=type=cache,mode=0777,target=/root/.m2: not found

**Comment by aurambaj** [comment]
were you using: https://docs.docker.com/develop/develop-images/build_enhancements/?

**Comment by martijnmichel** [comment]
I tried to use buildkit prepending the env vars DOCKER_BUILDKIT=1 but that does not seem to work. Using the ms docker file atm, lets see if that works

**Comment by aurambaj** [comment]
Regarding `brew`, I suspect you've followed the [getting started guide](https://www.mojito.global//docs/guides/getting-started/)? The first line says Java 1.8 is required.

The docker compose files are more of a sandbox that I've been using, but it is not currently documented as a solution to run Mojito. After the starting guide, the current installation instruction are [here](https://www.mojito.global//docs/guides/install-springboot2/). 

With my current docker setup and what's on master, `docker-compose` is working fine for me. It is probably due to different setup in docker, but if you don't share error logs I can't guess what's going on.

**Comment by aurambaj** [comment]
Did some clean up and improvement to docker images to try new Java runtimes in  https://github.com/box/mojito/commit/fc9501edbcd8d47573eab165543e6087b5808a9c
