### ISSUE TITLE
[Question] Are there any examples (e.g. GitLab CI)?

### ISSUE THREAD

**Issue by matzeeable** [box/mojito#689]
Hey!

We want to introduce Continuous Localization to our project, and I stumbled over this promising tool. I think I have understood the main concepts:

- Mojito is like a GIT repository. It handles multiple branches, and we can push new extracted strings and pull at build time

Now, I would be happy to hear some thoughts how we can implement this to our existing GIT repository (GitLab) and implement it within our CI/CD. We have already multiple `.po` files inside it. All our localization files are currently synced with our GIT. But as I have understood Mojito, we should not sync them with our GIT (put them to `.gitignore`), correct?

My initial thoughts are as this:

- In our CI/CD we have a job to build our application (`build`)
- We want to add a job that extracts strings to `.pot,.po,.mo` (for this, we are using [`wp i18n make-pot`](https://developer.wordpress.org/cli/commands/i18n/make-pot/)), but before we need to [pull from mojito](https://www.mojito.global//docs/guides/generating-localized-files/) to keep language cache intact (for the current branch)
- We need to [push](https://www.mojito.global//docs/guides/string-extraction/) the updated `.pot,.po` files back to mojito
- We are doing some translation within the UI
- The next time the `build` runs, it needs to pull again from mojito and use the new translations

Do you have any example how this could work with a CI/CD? Unfortunately I did not find anything in your documentation. For example, how do we execute the CLI to an external host (the mojito docker environment is not running at the same host as the CI/CD)?

Regards,
Matthew 😊

**Comment by aurambaj** [comment]
to keep things simple you can have 1 job that runs on a schedule and does something along those lines:
- git checkout
- run the extractor: code to `pot` files (source strings)
- mojito push: will push your `pot` files (source strings) to mojito for translation
- mojito pull: will generate `po` files for each `pot` file
- compilation step `po` files to `mo` files
- git commit 

(I'm not sure to undertand what you mean by "But as I have understood Mojito, we should not sync them with our GIT (put them to .gitignore), correct")

**Comment by ehoogerbeets** [comment]
Jean, I think what Matthias meant is that during a build, the goal is to produce the .mo files and then include them directly into the package it is building. In that case, the generated .po and .mo files do not need to be committed to git and pushed to the server. They are just generated on the fly and packaged immediately.

@matzeeable The alternate way of doing things is to separate the job for making builds from the job that does translation. That is, have 2 jobs. The translation job should run on a regular basis (once an hour maybe?) and do the steps that Jean outlined above. At the end of the script, it commits the .po and .mo files to git. That way, when it comes time to do a build, the most up-to-date files are already there in git. This has a few advantages:

1. If your engineers want to preview the translations for whatever reason before merging them to your main branch, that is also possible. In that case, the translation job can commit the .po or .mo files to a branch, push that branch to the server, then create a PR for the engineers to look at and merge when they are ready.
2. The translation job will run only on the git branches you select. If you generate the .po/.mo files during every CI build for every feature branch, then when the CI job pushes the strings to mojito, it may have a different set of strings in it than other feature branches. This causes some of the strings to be marked as "unused" in mojito because your feature has a string that the other features don't and vice versa. If your translation job only runs on the "development" or "main" branch (or whatever the main merge target branch is) then it will have a consistent set of strings that are marked as used/unused. Also, when a CI build runs on a PR, the strings in that PR may change as the engineer addresses all of the reviewer's comments and fixes the problems they find.
3. Having the .po/.mo files available in git means that the engineers will be able easily to run and test their code locally in other locales. We all know of that one bug that only occurs in, let's say, French but not in English so you have to run your local code in French in order to debug it! Alternately, if the .po/.mo files are not in git, the engineers could have a script that calls the mojito-cli to generate the .po/.mo files whenever they want them so they can test locally.
4. Having the .mo/.po files in git makes for an easily reproducible build. That is, you can rebuild an old build for testing a customer-reported bug or to make an emergency bug fix and it will have the right set of strings in it. Without the strings in git, you have to regenerate the .po/.mo files from what exists today in mojito. However, the translations may have been updated in mojito by the translators or reviewers or engineers and do not necessarily reflect what the strings said in that old build you are trying to reproduce. (If we had tagging in mojito, that would resolve this problem, but currently we don't. Nudge nudge Jean. ;-) ) 

That comes to the 3rd way of doing things: generate the .po/.mo files in your build as you are doing now, but don't do extraction/mojito push. That way, you won't have the problem of strings existing in one feature branch but not another. Instead, there would be an extraction job (instead of a translation job) that runs on a regular basis on select branches, and all it does is generate the .pot files and pushes them to mojito, then exits.

**Comment by aurambaj** [comment]
@ehoogerbeets 

`2.` [Mojito now support branches](https://www.mojito.global//docs/guides/branching/), if using that, the used/unused issu is not a problem anymore. 
`4.` Is it really something needed though in Mojito? Would you use it if it was available? I think having the file in git is the way to go if trying to accomplish build reproducibility.

**Comment by matzeeable** [comment]
Hey @ehoogerbeets and @aurambaj !

Thanks for your replies, this is really helpful to me.

> (I'm not sure to undertand what you mean by "But as I have understood Mojito, we should not sync them with our GIT (put them to .gitignore), correct")

> In that case, the generated .po and .mo files do not need to be committed to git and pushed to the server. They are just generated on the fly and packaged immediately.

Yeah, it is correct what @ehoogerbeets says. In general, I want to completely exclude the localization files from our GIT repository and `.gitignore`' them. I also think about to entirely ignore the source files (`.pot`), too - my experience is, that they are producing many headaches and merge conflicts - developers should not think about dealing with translation files and simply use the following workflow:

1. Developer commits and pushes to repository
1. Our CI/CD detected changes of the source code itself and extracts the strings to a `.pot`
1. The updated `.pot` is pushed to mojito
1. Our CI/CD builds our application, but before it pulls the translation files from mojito
1. Developer navigates to the mojito app and translates some texts

*When are new translations applied in our application?*

We have two scenarios here:

1. Developers are working in feature branches and can only merge to `develop` via merge request. The MR gets merged to `develop` and afterwards to `main`. The next CI/CD pipeline will detect the changes of the package and proceeds the same steps as above (Extract strings to `.pot`, pushes to mojito, pulls from mojito and build the application). **All fine, the new build has updated translations in the target branch.**
1. We have review applications. As soon as someone pushes to the GIT repository, our CI/CD is creating review applications so the developers can see their changes in real. Developers now want to translate the new texts and see them in their review application: Developers need to navigate to the CI/CD pipeline and restart the `build` and `review` job. **The review application has the newest localization files and the developer can "test" the translations.**

> Mojito now support branches, if using that, the used/unused issu is not a problem anymore.

This is awesome, and I think this finally makes my approach to work.

I hope I made things clear! No further questions and I will give it a try next week.

Regards,
Matthew 😊
